name: checkers-ai-web
channels:
  - conda-forge
dependencies:
  - python=3.10
  - fastapi=0.115.12
  - uvicorn=0.34.3
  - pydantic=2.11.5
  - numpy=1.26.4
  - gym=0.21.0
  - stable-baselines3=1.8.0
  - wandb=0.15.0
  - hydra-core=1.2.0
  - omegaconf=2.2.3
  - pip
  - pip:
    - git+https://github.com/falcondai/gym-checkers.git#egg=checkers
