version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - checkers-net
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - checkers-net
    restart: always

networks:
  checkers-net:
    driver: bridge
