version: "3"
services:
  backend:
    build: ./backend
    ports: ["8000:8000"]

  frontend:
    build: ./frontend
    ports: ["3000:80"]
    environment:
      - VITE_API_URL=/api
      - VITE_WS_URL=/api
    depends_on:
      - backend

  # simple Nginx reverse proxy (optional)
  proxy:
    image: nginx:alpine
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    ports: ["80:80"]
    depends_on: [frontend, backend]
