version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://localhost:8000"
        VITE_WS_URL:  "ws://localhost:8000"
    ports:
      - "3000:80"
    depends_on:
      - backend
